package(default_visibility = ["//visibility:public"])

load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "StringReverse",
    srcs = ["String+StringReverse.swift"],
    deps = [
        "//DataStructures/Stack",
    ],
)
